### ISSUE TITLE
Can't seem to run the PPO example

### ISSUE THREAD

**Issue by VinHylme** [maik97/wacky-rl#1]
Hello, When i try to run the PPO example i get an error which states the following:
    agent = PPO(env)
  File "/usr/local/lib/python3.8/dist-packages/wacky_rl/agents/ppo.py", line 39, in __init__
    self.actor.nature_network(256)
AttributeError: 'WackyModel' object has no attribute 'nature_network'

Any ideas why?
thanks

**Comment by maik97** [comment]
Hi, thank you. Fixed it!
